server:
    port : 8090
####### resource server configuration properties
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${OAUTH_ISSUER_URI}

logging:
    level:
        org.elasticsearch.client.RestClient: ERROR